### ISSUE TITLE
Muscle doesn't contract

### ISSUE THREAD

**Issue by Lukuas31415** [Lukuas31415/BA#11]
The muscle with the model on the branch bug-prestretch, where the fibers are included in the prestretch, is not contracting at all after the prestretch. I couldn't find out why, because I don't know enough about how the solvers work. 
@carme-hp

**Comment by Lukuas31415** [comment]
The fibers are being activated, the activation flows through the fibers as it should, but the fibers are not reacting/contracting and neither does the muscle. I have compared the config and cpp files of the setups with the correct prestretch and the old one, and I cannot find a difference in the contraction parts. I don't know where the mistake could lie.

**Comment by carme-hp** [comment]
After looking into the `solver_structure.txt` file which is automatically generated after running the example I realised that there were connected slots between prestretch and the contraction. The slots were automatically connected because they had the same name, and I think this resulted in the prestretch simulation prescribing 0 activation and stress to the contraction 3D mesh. I solved this by modifying the slots name in the contraction simulation, so that they are no longer the same as in the prestretch simulation: 

>           "MuscleContractionSolver": {
>             "slotNames":                    ["lambdaContraction", "ldotContraction", "gammaContraction", "TContraction"],
>             #"slotNames":                    ["lambda", "ldot", "gamma", "T"],

**Comment by Lukuas31415** [comment]
With this addition it works just as we want.
